version: 1.0.{build}
image: WMF 5
install:
- ps: "Install-PackageProvider -Name NuGet –Force\nInstall-Package -Name Pester -ProviderName PowerShellGet -Scope AllUsers -Force\nInstall-Module -Name PSScriptAnalyzer -Scope AllUsers –Force\nImport-Module -Name Pester\nImport-Module -Name PSScriptAnalyzer"
build: off
test_script:
- ps: >-
    $testResultsFile = ".\TestsResults.xml"

    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))

    If ($results.FailedCount -gt 0) {
      throw "$($results.FailedCount) tests failed."
    }
artifacts:
- path: '*.ps1'
- path: '*.exe'
- path: '*.config'
- path: Files\**\*
- path: SupportFiles\**\*
- path: AppDeployToolkit\**\*